openapi: 3.0.4
info:
  title: Concursos Públicos BR API
  version: 0.0.1
  description: API para consulta de concursos públicos por UF
servers:
  - url: /
paths:
  /api/concursos/concursos-publicos:
    get:
      tags:
        - Concursos
      operationId: proxyGet
      summary: Retorna concursos públicos por UF
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: uf
          required: true
          schema:
            type: string
            nullable: false
            pattern: ^(ac|al|ap|am|ba|ce|df|es|go|ma|mt|ms|mg|pa|pb|pr|pe|pi|rj|rn|rs|ro|rr|sc|sp|se|to|AC|AL|AP|AM|BA|CE|DF|ES|GO|MA|MT|MS|MG|PA|PB|PR|PE|PI|RJ|RN|RS|RO|RR|SC|SP|SE|TO)+$
            minLength: 2
            maxLength: 2
          description: Unidade Federativa (ex. sp, rj)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcursoPublicoRepresentation'
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/token:
    post:
      tags:
        - Auth
      operationId: generateToken
      summary: Gera um token JWT
      description: Endpoint público para geração de token JWT de demonstração
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequestRepresentation'
      responses:
        '200':
          description: Token gerado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponseRepresentation'
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ConcursoPublicoRepresentation:
      type: object
      description: Representação de concursos públicos
      properties:
        estado:
          type: string
        uf:
          type: string
        concursosAbertos:
          type: array
          items:
            $ref: '#/components/schemas/ConcursoRepresentation'
        concursosPrevistos:
          type: array
          items:
            $ref: '#/components/schemas/ConcursoRepresentation'

    ConcursoRepresentation:
      type: object
      properties:
        orgao:
          type: string
        vagas:
          type: string
    TokenRequestRepresentation:
      type: object
      properties:
        username:
          type: string
        roles:
          type: array
          items:
            type: string
      required:
        - username
    TokenResponseRepresentation:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    ErrorResponse:
      type: object
      description: Estrutura padrão de erro
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          format: int32
        error:
          type: string
        message:
          type: string
        path:
          type: string
      required:
        - status
        - error









